In [60]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [61]:
ch = pd.read_csv('churn.csv')
ch.head(7)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No

Steps involved in model building
1. problem statement ---- come to know the target variable
2. data gathering
3. data cleaning / data pre-processing
4. sampling divide data into train and test ---- train data and build the model and test data to do the testing
* mode data s in train (80%) and test(20%)
* testing should not be done on same data on which model was build
* sampling should be random
5. fit the model ---- build / train the model
6. do the prediction and evaluate the model ---- basically check the performane of the model

1. problem statement ---- predict the status
2. data gathering ---- data already provided
3. data cleaning ---- remove the nulls

In [62]:
ch.isnull().sum()[ch.isnull().sum() > 0]
# it will find the null values and give the count of null values

Series([], dtype: int64)

* labels (non-numeric data)
* model should be build only on numbers
* ordinal data should be converted using replace and nominal labelencoder should be used

In [63]:
ch_select_dtype = ch.select_dtypes(include = ['object'])
ch_select_dtype.head(5)

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
0,7590-VHVEG,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,No
1,5575-GNVDE,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,1889.5,No
2,3668-QPYBK,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,108.15,Yes
3,7795-CFOCW,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),1840.75,No
4,9237-HQITU,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,151.65,Yes

In [64]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [65]:
ch.Contract.replace({'Month-to-month': 0, 'One year': 1, 'Two year': 2}, inplace = True)
ch.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,1,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,0,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,0,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,0,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,0,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,1,No,Bank transfer (automatic),56.15,3487.95,No

In [66]:
ch.drop(['customerID'], axis = 1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,1,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,1,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,1,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,0,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,0,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,2,Yes,Bank transfer (automatic),105.65,6844.5,No

In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [68]:
le.fit_transform(ch.TotalCharges)

array([2505, 1466,  157, ..., 2994, 2660, 5407], shape=(7043,))

In [69]:
ch.TotalCharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [70]:
ch.TotalCharges = ch.TotalCharges.replace({'':np.nan})
# converting space to nulls

In [71]:
ch.TotalCharges.isnull().sum()

np.int64(0)

In [72]:
ch[ch.select_dtypes(include='object').columns] = ch[ch.select_dtypes(include='object').columns].apply(le.fit_transform)

In [73]:
from sklearn.model_selection import train_test_split
# train_test_split  spilts the data into train and test

In [74]:
ch_train, ch_test = train_test_split(ch, test_size = 0.2)
ch_train_x = ch_train.iloc[:,0:-1]
ch_train_y = ch_train.iloc[:,-1]
ch_test_x = ch_test.iloc[:,0:-1]
ch_test_y = ch_test.iloc[:,-1]

In [75]:
from sklearn.metrics import confusion_matrix, classification_report

In [76]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[921 109]
 [190 189]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1030
           1       0.63      0.50      0.56       379

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [77]:
from sklearn.tree  import DecisionTreeClassifier
lr = DecisionTreeClassifier()
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[840 190]
 [206 173]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1030
           1       0.48      0.46      0.47       379

    accuracy                           0.72      1409
   macro avg       0.64      0.64      0.64      1409
weighted avg       0.72      0.72      0.72      1409

In [78]:
from sklearn.ensemble import RandomForestClassifier
lr = RandomForestClassifier(class_weight = 'balanced')
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[949  81]
 [222 157]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.81      0.92      0.86      1030
           1       0.66      0.41      0.51       379

    accuracy                           0.78      1409
   macro avg       0.74      0.67      0.69      1409
weighted avg       0.77      0.78      0.77      1409

Over Sampling

In [79]:
ch_train.Churn.value_counts()

Churn
0    4144
1    1490
Name: count, dtype: int64

In [80]:
df=ch_train[ch_train.Churn==1]
df.shape

(1490, 21)

Select al records which belong to class 1

In [81]:
ch_train=pd.concat([ch_train,df.iloc[0:1000]])
ch_train.Churn.value_counts()

Churn
0    4144
1    2490
Name: count, dtype: int64

In [82]:
ch_train_x = ch_train.iloc[:,0:-1]
ch_train_y = ch_train.iloc[:,-1]
ch_test_x = ch_test.iloc[:,0:-1]
ch_test_y = ch_test.iloc[:,-1]

In [83]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[854 176]
 [146 233]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.85      0.83      0.84      1030
           1       0.57      0.61      0.59       379

    accuracy                           0.77      1409
   macro avg       0.71      0.72      0.72      1409
weighted avg       0.78      0.77      0.77      1409

In [84]:
from sklearn.tree  import DecisionTreeClassifier
lr = DecisionTreeClassifier()
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[849 181]
 [198 181]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.81      0.82      0.82      1030
           1       0.50      0.48      0.49       379

    accuracy                           0.73      1409
   macro avg       0.66      0.65      0.65      1409
weighted avg       0.73      0.73      0.73      1409

In [85]:
from sklearn.ensemble import RandomForestClassifier
lr = RandomForestClassifier(class_weight = 'balanced')
lr.fit(ch_train_x,ch_train_y)
predictions=lr.predict(ch_test_x)
tab=confusion_matrix(ch_test_y,predictions)
print(tab)
print("------------------------------------------------------")
print(classification_report(ch_test_y,predictions))

[[902 128]
 [198 181]]
------------------------------------------------------
              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1030
           1       0.59      0.48      0.53       379

    accuracy                           0.77      1409
   macro avg       0.70      0.68      0.69      1409
weighted avg       0.76      0.77      0.76      1409

In [86]:
feat_imp = pd.DataFrame( {'Features' :ch_train_x.columns, 'Score' : lr.feature_importances_})
feat_imp = feat_imp.sort_values('Score' , ascending= False)
feat_imp

            Features     Score
5             tenure  0.144014
18    MonthlyCharges  0.134594
19      TotalCharges  0.122681
15          Contract  0.117545
0         customerID  0.115905
9     OnlineSecurity  0.051582
12       TechSupport  0.044679
17     PaymentMethod  0.043351
8    InternetService  0.036224
10      OnlineBackup  0.024579
11  DeviceProtection  0.022438
1             gender  0.020202
16  PaperlessBilling  0.019937
7      MultipleLines  0.018840
3            Partner  0.018299
14   StreamingMovies  0.015535
4         Dependents  0.015425
13       StreamingTV  0.015024
2      SeniorCitizen  0.014411
6       PhoneService  0.004735

In [87]:
import pickle

# Save trained model
pickle.dump(lr, open("churn_model.pkl", "wb"))